#服务端口，随便起
server:
  port: 8085
  tomcat:
    max-swallow-size: 400MB #重要的一行，修改tomcat的吞吐量
#服务名称
spring:
  application:
    name: activity-server
  datasource:
    url: jdbc:mysql://localhost:3306/digital_club_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 400MB  #单个文件最大
      max-request-size: 400MB #单个请求文件总和最大

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

