# gateway端口
server:
  port: 80

# 端口服务设置
spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      enabled: true


# eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11011/eureka/
  instance:
    prefer-ip-address: true

management:
  #  health:
  #    redis:
  #      enabled: false  #防止因为redis而导致健康检查不过，导致在admin中显示应用状态为down
  #    mail:
  #      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"   #这里因为是测试可以用*，暴露所有，但生产环境需要特别设置
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
  file:
    name: E:\Code\Java_Projects\2024_6_25\Digital_Hundred_Clubs\backend\logs\${spring.application.name}\output.log
  config: classpath:logging/logback-spring.xml


