# gateway端口
server:
  port: 80

# 端口服务设置
spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      enabled: true


# eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11011/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug


