#服务端口，随便起
server:
  port: 8084
  tomcat:
    max-swallow-size: 400MB #重要的一行，修改tomcat的吞吐量
#服务名称
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/digital_club_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 400MB  #单个文件最大
      max-request-size: 400MB #单个请求文件总和最大
  mail:
    #smtp服务主机
    host: smtp.163.com
    #端口号
    port: 465
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: g122055009@163.com
    #授权码
    password: ZMKSCGVUPIPIBIGB
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

