#服务端口，随便起
server:
  port: 11011
#服务名称
spring:
  application:
    name: eureka-server

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/
    register-with-eureka: false
    fetch-registry: false

