#服务端口，随便起
server:
  port: 11011
#服务名称
spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://localhost:3306/DigitalClub?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '030520'
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/
    register-with-eureka: false
    fetch-registry: false

