package org.example.enums;

public enum ResultCode {
    //AUTH
    REGISTER_LOGIN(1),
    ADMIN_LOGIN(9),
    GET_IMAGE_VERIFY_CODE(39),
    GET_ENUM_LIST(41),

    //STUDENT
    GET_USER_INFO(3),
    UPDATE_USER_INFO(4),


    //CLUB
    GET_CLUB_INFO(2),
    ADD_CLUB_APPLICATION(5),
    GET_SINGLE_CLUB_ACTIVITY_NOTICE(6),
    GET_CLUB_INTRODUCTION(7),
    GET_ALL_CLUB_MEMBER(8),
    GET_CLUB_ACTIVITY_LIST(14),
    GET_CLUB_APPLY_LIST(15),
    AGREE_CLUB_APPLY(16),
    REJECT_CLUB_APPLY(17),
    GET_CLUB_EVALUATE_INFO(20),
    DELETE_CLUB_MEMBER(22),
    UPDATE_CLUB_MEMBER(23),
    ADD_CLUB_MEMBER(24),
    UPDATE_CLUB_INFO(25),
    GET_TOP_TEN_CLUB(32),
    ADD_CLUB_ANNUAL_AUDIT(34),
    ADD_CLUB_EVALUATION(35),
    GET_CLUB_NOTICE_LIST(36),
    ADD_NOTICE(37),
    ADD_MEETING(38),
    UPDATE_CLUB_DESCRIPTION(40),

    GET_CLUB_AWARDS(45),
    GET_CLUB_MEETINGS(46),
    ADD_CLUB_MEMBERSHIP_APPLICATION(47),
    GET_CLUB_APPLICATION_INFO(49),
    GET_CLUB_ANNUL_INFO(50),
    GET_CLUB_EVALUATION(51),
    GET_CLUB_DETAIL(52),
    GET_THIS_YEAR_CLUB_ANNUL_INFO(59),



    //ACTIVITY
    GET_ACTIVITY_INFO(12),
    GET_ALL_ACTIVITY_INFO(13),
    ADD_ACTIVITY(18),
    ADD_PERSONAL_PERFORMANCE(29),
    ADD_activityPerformance(30),
    GET_LATEST_ACTIVITY(31),
    JOIN_ACTIVITY(48),

    //ADMIN
    GET_ADMIN_INFO(10),
    UPDATE_ADMIN_INFO(11),
    ADD_BACKBONE_EVALUATION(19),
    GET_ALL_BACKBONE_EVALUATION(26),
    GET_ALL_CLUB_ANNUAL(27),
    GET_ALL_CLUB_EVALUATION(28),
    GET_SPECIAL_CLUB_BACKBONE(42),
    GET_SPECIAL_CLUB_ANNUAL(43),
    GET_SPECIAL_CLUB_TEACHER(44),
    PASS_CLUB_APPROVAL(53),
    UN_PASS_CLUB_APPROVAL(54),
    PASS_ACTIVITY_APPROVAL(55),
    UN_PASS_ACTIVITY_APPROVAL(56),
    PASS_CLUB_BACK_BONE_APPROVAL(57),
    UN_PASS_CLUB_BACK_BONE_APPROVAL(58),
    PASS_CLUB_ANNUL_APPROVAL(60),
    UN_PASS_CLUB_ANNUL_APPROVAL(61),
    PASS_CLUB_EVALUATION_APPROVAL(62),
    UN_PASS_CLUB_EVALUATION_APPROVAL(63),

    //file-server
    UPLOAD_IMAGE(21),
    UPLOAD_FILE(33);



    private final int code;


    ResultCode(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
