#服务端口，随便起
server:
  port: 8083
  tomcat:
    max-swallow-size: 400MB #重要的一行，修改tomcat的吞吐量
#服务名称
spring:
  application:
    name: file-server
  servlet:
    multipart:
      max-file-size: 400MB  #单个文件最大
      max-request-size: 400MB #单个请求文件总和最大

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/
  instance:
    prefer-ip-address: true

management:
  #  health:
  #    redis:
  #      enabled: false  #防止因为redis而导致健康检查不过，导致在admin中显示应用状态为down
  #    mail:
  #      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"   #这里因为是测试可以用*，暴露所有，但生产环境需要特别设置
  endpoint:
    health:
      show-details: always


logging:
  file:
    name: E:\Code\Java_Projects\2024_6_25\Digital_Hundred_Clubs\backend\logs\${spring.application.name}\output.log
  config: classpath:logging/logback-spring.xml