#服务端口，随便起
server:
  port: 8086
  tomcat:
    max-swallow-size: 400MB #重要的一行，修改tomcat的吞吐量
#服务名称
spring:
  application:
    name: admin-server
  datasource:
    url: jdbc:mysql://localhost:3306/digital_club_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 400MB  #单个文件最大
      max-request-size: 400MB #单个请求文件总和最大

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus-join:
  #是否打印 mybatis plus join banner 默认true
  banner: true
  #全局启用副表逻辑删除(默认true) 关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  #拦截器MappedStatement缓存(默认true)
  ms-cache: true
  #表别名(默认 t)
  table-alias: t
  #副表逻辑删除条件的位置，支持where、on
  #默认ON （1.4.7.2及之前版本默认为where）
  logic-del-type: on

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/
  instance:
    prefer-ip-address: true

management:
  #  health:
  #    redis:
  #      enabled: false  #防止因为redis而导致健康检查不过，导致在admin中显示应用状态为down
  #    mail:
  #      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"   #这里因为是测试可以用*，暴露所有，但生产环境需要特别设置
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: E:\Code\Java_Projects\2024_6_25\Digital_Hundred_Clubs\backend\logs\${spring.application.name}\output.log
  config: classpath:logging/logback-spring.xml