export const APIEventEnum = {
    // 请求事件
    request: 'request',

    // 请求成功事件
    loginSuccess: 'loginSuccess',
    postAdminLoginSuccess: 'postAdminLoginSuccess',
    getClubsInfoSuccess: 'getClubsInfoSuccess',
    getUserInfoSuccess: 'getUserInfoSuccess',
    getClubActAndNtcSuccess: 'getClubActAndNtcSuccess',
    getClubIntroductionSuccess: 'getClubIntroductionSuccess',
    getClubMembersSuccess: 'getClubMembersSuccess',
    getAdminInfoSuccess: 'getAdminInfoSuccess',
    getActivityInfoSuccess: 'getActivityInfoSuccess',
    getActivitiesInfoSuccess: 'getActivitiesInfoSuccess',
    getClubActivityListSuccess: 'getClubActivityListSuccess',
    getClubApplyListSuccess: 'getClubApplyListSuccess',
    postAgreeClubApplySuccess: 'postAgreeClubApplySuccess',
    postRejectClubApplySuccess: 'postRejectClubApplySuccess',
    postNewActivitySuccess: 'postNewActivitySuccess',
    postBackBoneEvaluateSuccess: 'postBackBoneEvaluateSuccess',
    getClubEvaluateInfoSuccess: 'getClubEvaluateInfoSuccess',
    uploadImageSuccess: 'uploadImageSuccess',
    postDeleteClubMemberSuccess: 'postDeleteClubMemberSuccess',
    postAddClubMemberSuccess: 'postAddClubMemberSuccess',
    postUpdateClubMemberSuccess: 'postUpdateClubMemberSuccess',
    postUpdateClubInfoSuccess: 'postUpdateClubInfoSuccess',
    getBackBoneEvaluationsSuccess: 'getBackBoneEvaluationsSuccess',
    getClubAnnualsSuccess: 'getClubAnnualsSuccess',
    getClubEvaluationsSuccess: 'getClubEvaluationsSuccess',
    postPersonalPerformanceSuccess: 'postPersonalPerformanceSuccess',
    postActivityPerformanceSuccess: 'postActivityPerformanceSuccess',
    getLatestActivitiesSuccess: 'getLatestActivitiesSuccess',
    getTopTenClubsSuccess: 'getTopTenClubsSuccess',
    postUserInfoSuccess: 'postUserInfoSuccess',
    postNewClubApplySuccess: 'postNewClubApplySuccess',
    uploadFileSuccess: 'uploadFileSuccess',
    postClubAnnualAuditFormSuccess: 'postClubAnnualAuditFormSuccess',
    postClubEvaluationFormSuccess: 'postClubEvaluationFormSuccess',
    getClubNoticeListSuccess: 'getClubNoticeListSuccess',
    postNewNoticeSuccess: 'postNewNoticeSuccess',
    postNewMeetingSuccess: 'postNewMeetingSuccess',
    getImageVerifyCodeSuccess: 'getImageVerifyCodeSuccess',
    postUpdateClubDescriptionSuccess: 'postUpdateClubDescriptionSuccess',
    getEnumListSuccess: 'getEnumListSuccess',
    getMyClubAnnualExamDataSuccess: 'getMyClubAnnualExamDataSuccess',
    getMyClubBackboneExamDataSuccess: 'getMyClubBackboneExamDataSuccess',
    getMyClubTeacherExamDataSuccess: 'getMyClubTeacherExamDataSuccess',
    getAssociationAwardsSuccess: 'getAssociationAwardsSuccess',
    getMeetingsSuccess: 'getMeetingsSuccess',
    postJoinClubSuccess: 'postJoinClubSuccess',
    postJoinActivitySuccess: 'postJoinActivitySuccess',
    getClubApprovalSuccess:'getClubApprovalSuccess',
    getClubAnnualSuccess:'getClubAnnualSuccess',
    getThisYearClubAnnualSuccess:'getThisYearClubAnnualSuccess',
    getClubAwardInfoSuccess:'getClubAwardInfoSuccess',
    getClubInfoSuccess:'getClubInfoSuccess',
    passClubApprovalSuccess:'passClubApprovalSuccess',
    unPassClubApprovalSuccess:'unPassClubApprovalSuccess',
    passCollegeClubApprovalSuccess: 'passCollegeClubApproval',
    unPassCollegeClubApprovalSuccess: 'unPassCollegeClubApprovalSuccess',
    passActivityApprovalSuccess:'passActivityApprovalSuccess',
    unPassActivityApprovalSuccess:'unPassActivityApprovalSuccess',
    passBackboneAwardsReviewSuccess:'passBackboneAwardsReviewSuccess',
    unPassBackboneAwardsReviewSuccess:'unPassBackboneAwardsReviewSuccess',
    passClubAnnualReviewSuccess:'passClubAnnualReviewSuccess',
    unPassClubAnnualReviewSuccess:'unPassClubAnnualReviewSuccess',
    passClubAwardReviewSuccess:'passClubAwardReviewSuccess',
    unPassClubAwardReviewSuccess:'unPassClubAwardReviewSuccess',

    // 请求失败事件
    incorrectInput: 'incorrectInput',
    registerError: 'registerError',
}

export const APIEnum = {
    postLogin: 'postLogin',
    postRegister: 'postRegister',
    getClubsInfo: 'getClubsInfo',
    getVerifyCode: 'getVerifyCode',
    getUserInfo: 'getUserInfo',
    postUserInfo: 'postUserInfo',
    postNewClubApply: 'postNewClubApply',
    getClubActAndNtc: 'getClubActAndNtc',
    getClubIntroduction: 'getClubIntroduction',
    getClubMembers: 'getClubMembers',
    postAdminLogin: 'postAdminLogin',
    getAdminInfo: 'getAdminInfo',
    postAdminInfo: 'postAdminInfo',
    getActivityInfo: 'getActivityInfo',
    getActivitiesInfo: 'getActivitiesInfo',
    getClubActivityList: 'getClubActivityList',
    getClubApplyList: 'getClubApplyList',
    postAgreeClubApply: 'postAgreeClubApply',
    postRejectClubApply: 'postRejectClubApply',
    postNewActivity: 'postNewActivity',
    postBackBoneEvaluate: 'postBackBoneEvaluate',
    // getClubEvaluateInfo: 'getClubEvaluateInfo',
    uploadImage: 'uploadImage',
    postDeleteClubMember: 'postDeleteClubMember',
    postAddClubMember: 'postAddClubMember',
    postUpdateClubMember: 'postUpdateClubMember',
    postUpdateClubInfo: 'postUpdateClubInfo',
    getBackBoneEvaluations: 'getBackBoneEvaluations',
    getClubAnnuals: 'getClubAnnuals',
    getClubEvaluations: 'getClubEvaluations',
    postPersonalPerformance: 'postPersonalPerformance',
    postActivityPerformance: 'postActivityPerformance',
    getLatestActivities: 'getLatestActivities',
    getTopTenClubs: 'getTopTenClubs',
    uploadFile: 'uploadFile',
    postClubAnnualAuditForm: 'postClubAnnualAuditForm',
    postClubEvaluationForm: 'postClubEvaluationForm',
    getClubNoticeList: 'getClubNoticeList',
    postNewNotice: 'postNewNotice',
    postNewMeeting: 'postNewMeeting',
    getImageVerifyCode: 'getImageVerifyCode',
    postUpdateClubDescription: 'postUpdateClubDescription',
    getEnumList: 'getEnumList',
    getMyClubAnnualExamData: 'getMyClubAnnualExamData',
    getMyClubBackboneExamData: 'getMyClubBackboneExamData',
    getMyClubTeacherExamData: 'getMyClubTeacherExamData',
    getAssociationAwards: 'getAssociationAwards',
    getMeetings: 'getMeetings',
    postJoinClub: 'postJoinClub',
    postJoinActivity: 'postJoinActivity',
    getClubApproval:'getClubApproval',
    getClubAnnual:'getClubAnnual',
    getThisYearClubAnnual:'getThisYearClubAnnual',
    getClubAwardInfo:'getClubAwardInfo',
    getClubInfo:'getClubInfo',
    passClubApproval:'passClubApproval',
    unPassClubApproval:'unPassClubApproval',
    passCollegeClubApproval: 'passCollegeClubApproval',
    unPassCollegeClubApproval: 'unPassCollegeClubApproval',
    passActivityApproval:'passActivityApproval',
    unPassActivityApproval:'unPassActivityApproval',
    passBackboneAwardsReview:'passBackboneAwardsReview',
    unPassBackboneAwardsReview:'unPassBackboneAwardsReview',
    passClubAnnualReview:'passClubAnnualReview',
    unPassClubAnnualReview:'unPassClubAnnualReview',
    passClubAwardReview:'passClubAwardReview',
    unPassClubAwardReview:'unPassClubAwardReview',
}


// 路由
export const RouterEventEnum = {
    push: 'push',
    go: 'go',
}

// 存储
export const StoreEventEnum = {
    set: 'set',
}

export const StoreEnum = {
    setInit: 'setInit',
    setClubsData: 'setClubsData',
    setUserInfo: 'setUserInfo',
    setRouteTabs: 'setRouteTabs',
    setParentRoute: 'setParentRoute',
    setclubsActAndNtc: 'setclubsActAndNtc',
    setClubId: 'setClubId',
    setAdminInfo: 'setAdminInfo',
    reset: 'reset',
    setAdminInit:'setAdminInit',
}

// 展示的社团类型
export const TypeEventEnum = {
    addType: 'addType',
    removeType: 'removeType',
}